
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 17 16:47:50 CST 2019
//----------------------------------------------------

package grammar_gxml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 62;
  public static final int PATH = 32;
  public static final int LCURL = 48;
  public static final int DEFECTO = 12;
  public static final int MINIMO = 31;
  public static final int HEX = 82;
  public static final int AUTO_REPRODUCCION = 33;
  public static final int NOTEQ = 68;
  public static final int CONTROL = 9;
  public static final int ENVIAR = 15;
  public static final int PLUSEQ = 56;
  public static final int VERDADERO = 44;
  public static final int TEXTO = 8;
  public static final int RBRACK = 53;
  public static final int COMMA = 74;
  public static final int POW = 64;
  public static final int LBRACK = 52;
  public static final int FALSO = 45;
  public static final int ALTO = 22;
  public static final int NOT = 73;
  public static final int ACCIONINICIAL = 18;
  public static final int LISTADATOS = 10;
  public static final int DESPLEGABLE = 38;
  public static final int STRINGLIT = 83;
  public static final int NEGRITA = 28;
  public static final int FUENTE = 26;
  public static final int NUM = 78;
  public static final int CONTENEDOR = 7;
  public static final int EQ = 47;
  public static final int TAM = 27;
  public static final int IMPORTAR = 5;
  public static final int LESSTHAN = 70;
  public static final int MULTIMEDIA = 13;
  public static final int SLASH = 4;
  public static final int PLUS = 60;
  public static final int CURSIVA = 29;
  public static final int LPAR = 50;
  public static final int TIMESEQ = 58;
  public static final int TIPO = 16;
  public static final int UNOT = 85;
  public static final int NOMBRE = 25;
  public static final int Y = 21;
  public static final int DQ = 46;
  public static final int X = 20;
  public static final int DIV = 63;
  public static final int Q = 76;
  public static final int ANCHO = 23;
  public static final int MORETHAN = 69;
  public static final int DOT = 75;
  public static final int NULO = 84;
  public static final int MUSICA = 39;
  public static final int EQEQ = 67;
  public static final int EOF = 0;
  public static final int BORDE = 24;
  public static final int RPAR = 51;
  public static final int REFERENCIA = 34;
  public static final int LESSTHANEQ = 66;
  public static final int SECUNDARIA = 43;
  public static final int DATO = 11;
  public static final int CLOSETAG = 3;
  public static final int IMAGEN = 41;
  public static final int CONTENIDO = 81;
  public static final int MINUS = 61;
  public static final int TEXTOAREA = 37;
  public static final int PRINCIPAL = 42;
  public static final int OR = 72;
  public static final int error = 1;
  public static final int BOTON = 14;
  public static final int DIVEQ = 59;
  public static final int ID = 77;
  public static final int COLOR = 17;
  public static final int MINUSMINUS = 55;
  public static final int ACCION = 35;
  public static final int NUMERICO = 36;
  public static final int MAXIMO = 30;
  public static final int PLUSPLUS = 54;
  public static final int VENTANA = 6;
  public static final int OPENTAG = 2;
  public static final int MORETHANEQ = 65;
  public static final int STRING = 80;
  public static final int ACCIONFINAL = 19;
  public static final int RCURL = 49;
  public static final int AND = 71;
  public static final int UMINUS = 86;
  public static final int VIDEO = 40;
  public static final int ID_L = 79;
  public static final int MINUSEQ = 57;
}

