
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 20 12:05:52 CST 2019
//----------------------------------------------------

package grammar_gdato;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 10;
  public static final int SLASH = 4;
  public static final int FALSO = 8;
  public static final int NULO = 9;
  public static final int LISTA = 5;
  public static final int STRING = 12;
  public static final int EOF = 0;
  public static final int OPENTAG = 2;
  public static final int ID = 11;
  public static final int CLOSETAG = 3;
  public static final int error = 1;
  public static final int VERDADERO = 7;
  public static final int PRINCIPAL = 6;
}

