
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 11 21:26:05 CST 2019
//----------------------------------------------------

package grammar_fs;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 55;
  public static final int ALCLIC = 43;
  public static final int LCURL = 46;
  public static final int DEFECTO = 11;
  public static final int MINIMO = 21;
  public static final int CREARBOTON = 39;
  public static final int NOTEQ = 69;
  public static final int PLUSEQ = 60;
  public static final int SEMI = 74;
  public static final int OPN = 31;
  public static final int VERDADERO = 3;
  public static final int SI = 13;
  public static final int OPI = 30;
  public static final int RBRACK = 51;
  public static final int OPE = 29;
  public static final int COMMA = 75;
  public static final int CREARNUMERICO = 37;
  public static final int POW = 57;
  public static final int LBRACK = 50;
  public static final int FALSO = 4;
  public static final int FUNCION = 15;
  public static final int CREARVIDEO = 42;
  public static final int FILTRAR = 22;
  public static final int NOT = 72;
  public static final int VAR = 5;
  public static final int CADA = 18;
  public static final int NUM = 78;
  public static final int EQ = 52;
  public static final int CREARDESPLEGABLE = 38;
  public static final int IMPORTAR = 7;
  public static final int CREARCAJA = 35;
  public static final int LESSTHAN = 65;
  public static final int BUSCAR = 23;
  public static final int UMINUSMINUS = 82;
  public static final int CREARTEXTO = 34;
  public static final int PLUS = 53;
  public static final int DETENER = 8;
  public static final int LPAR = 48;
  public static final int TIMESEQ = 62;
  public static final int CREARVENTANA = 32;
  public static final int UNOT = 84;
  public static final int IMPRIMIR = 6;
  public static final int CREARIMAGEN = 40;
  public static final int DIV = 56;
  public static final int Q = 77;
  public static final int CREARCONTENEDOR = 33;
  public static final int MORETHAN = 64;
  public static final int DOT = 76;
  public static final int MAP = 24;
  public static final int NULO = 2;
  public static final int REDUCE = 25;
  public static final int EQEQ = 68;
  public static final int EOF = 0;
  public static final int LEERGXML = 28;
  public static final int RPAR = 49;
  public static final int SELECCIONA = 9;
  public static final int CREARAREA = 36;
  public static final int LESSTHANEQ = 67;
  public static final int MINUS = 54;
  public static final int OR = 71;
  public static final int error = 1;
  public static final int UPLUSPLUS = 81;
  public static final int DIVEQ = 63;
  public static final int ALCERRAR = 45;
  public static final int ID = 79;
  public static final int MINUSMINUS = 59;
  public static final int SINO = 14;
  public static final int COLON = 73;
  public static final int INVERTIR = 19;
  public static final int MAXIMO = 20;
  public static final int CASO = 10;
  public static final int TODOS = 26;
  public static final int RETORNAR = 12;
  public static final int PLUSPLUS = 58;
  public static final int ALCARGAR = 44;
  public static final int MORETHANEQ = 66;
  public static final int STRING = 80;
  public static final int RCURL = 47;
  public static final int ASCENDENTE = 17;
  public static final int AND = 70;
  public static final int UMINUS = 83;
  public static final int DESCENDENTE = 16;
  public static final int MINUSEQ = 61;
  public static final int ALGUNO = 27;
  public static final int CREARREPRODUCTOR = 41;
}

